### ISSUE TITLE
Can't create mount

### ISSUE THREAD

**Issue by qrpike** [PressLabs/gitfs#197]
Ubuntu:14.04 ( using docker )

When I try to mount a github repo, this is the error I get:

```
Traceback (most recent call last):
  File "/usr/bin/gitfs/.bootstrap/_pex/pex.py", line 225, in execute
    self.execute_entry(entry_point, args)
  File "/usr/bin/gitfs/.bootstrap/_pex/pex.py", line 273, in execute_entry
    runner(entry_point)
  File "/usr/bin/gitfs/.bootstrap/_pex/pex.py", line 296, in execute_pkg_resources
    runner()
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/__init__.py", line 20, in mount
    start_fuse()
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/mounter.py", line 98, in start_fuse
    args = parse_args(parser)
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/mounter.py", line 38, in parse_args
    return Args(parser)
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/utils/args.py", line 61, in __init__
    self.config = self.build_config(parser.parse_args())
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/utils/args.py", line 70, in build_config
    return self.check_args(self.set_defaults(args))
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/utils/args.py", line 93, in check_args
    handler = SysLogHandler(address="/dev/log")
  File "/usr/lib/python2.7/logging/handlers.py", line 759, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib/python2.7/logging/handlers.py", line 787, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory
```

The repo is public and the directory I'm cloning into has 777 permissions. I've tried it also with no directory already created. Same error.

**Comment by vtemian** [comment]
By default, `gitfs` is trying to log in `/dev/log` (https://github.com/PressLabs/gitfs/blob/master/gitfs/utils/args.py#L93). If you don't have it, it will throw this ugly error. You can specify, at mount point, another logfile.

For now, it doesn't know how to fallback to another log file.

**Comment by qrpike** [comment]
I created the log dir.

Now I am getting this: 

`gitfs https://github.com/qrpike/CentOS-6-Quick-Install-Scripts.git /scripts -o debug=true`

```
Traceback (most recent call last):
  File "/usr/bin/gitfs/.bootstrap/_pex/pex.py", line 225, in execute
    self.execute_entry(entry_point, args)
  File "/usr/bin/gitfs/.bootstrap/_pex/pex.py", line 273, in execute_entry
    runner(entry_point)
  File "/usr/bin/gitfs/.bootstrap/_pex/pex.py", line 296, in execute_pkg_resources
    runner()
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/__init__.py", line 20, in mount
    start_fuse()
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/mounter.py", line 98, in start_fuse
    args = parse_args(parser)
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/mounter.py", line 38, in parse_args
    return Args(parser)
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/utils/args.py", line 61, in __init__
    self.config = self.build_config(parser.parse_args())
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/utils/args.py", line 70, in build_config
    return self.check_args(self.set_defaults(args))
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/utils/args.py", line 93, in check_args
    handler = SysLogHandler(address="/dev/log")
  File "/usr/lib/python2.7/logging/handlers.py", line 759, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib/python2.7/logging/handlers.py", line 787, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
```

**Comment by qrpike** [comment]
And if I specify /dev/null I get this:

```
root@76cf13c7210a:/# sudo gitfs https://github.com/qrpike/CentOS-6-Quick-Install-Scripts.git /scripts -o debug=true,log=/dev/null
fuse: failed to open /dev/fuse: Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/gitfs/.bootstrap/_pex/pex.py", line 225, in execute
    self.execute_entry(entry_point, args)
  File "/usr/bin/gitfs/.bootstrap/_pex/pex.py", line 273, in execute_entry
    runner(entry_point)
  File "/usr/bin/gitfs/.bootstrap/_pex/pex.py", line 296, in execute_pkg_resources
    runner()
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/__init__.py", line 20, in mount
    start_fuse()
  File "/root/.pex/install/gitfs-0.3.3-py2-none-any.whl.9e0c81d540e5018c3766cced5c105864e35d8bd4/gitfs-0.3.3-py2-none-any.whl/gitfs/mounter.py", line 111, in start_fuse
    subtype="gitfs")
  File "/root/.pex/install/fusepy-2.0.2-py2-none-any.whl.485379aada2e7509e0d631c6e35fe760bee9876a/fusepy-2.0.2-py2-none-any.whl/fuse.py", line 399, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```

**Comment by vtemian** [comment]
Nice :+1: I think that this is a more like a docker integration and missing documantation. We didn't test this yet, but I found a related issue regarding docker and fuse (https://github.com/docker/docker/issues/9448). 
It suppose to work if you add `--device /dev/fuse`, but I didn't test.

I will mark this issue as a bug and we'll start looking into it. Thanks!
