### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'pycparser' distribution was not found and is required by cffi

### ISSUE THREAD

**Issue by capnslipp** [PressLabs/gitfs#254]
I'm getting the following stacktrace and error when trying to run `gitfs ./.git /Volumes/gitfs-mount` from a git project dir.

```
Traceback (most recent call last):
  File "/usr/local/bin/gitfs", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2991, in <module>
    @_call_aside
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2977, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3004, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 662, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 970, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/gitfs/0.4.3/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 856, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycparser' distribution was not found and is required by cffi
```

* Installed `gitfs` about a week ago via Homebrew _(`brew install homebrew/fuse/gitfs`)_ under OS X El Capitan 10.11.5.
* `gitfs` version according to `brew info` is the latest version, `stable 0.4.3, HEAD`.
* `which python` resolves to `/usr/local/bin/python` (Homebrew's), and `python --version` is `Python 2.7.11`
* `pip` is `pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)`

I tried `pip install pycparser`; it completed with `Successfully installed pycparser-2.14`.  However, whenever running `gitfs` _(even `gitfs --version`)_, I still get the same stack trace as above.

**Comment by t-ionut** [comment]
This is related to https://github.com/PressLabs/gitfs/issues/196. There's a PR on homebrew-fuse waiting for approval. Closing
