### ISSUE TITLE
Installation error: Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by stianhoiland** [presslabs/gitfs#263]
Encountering this installation error on macOS Sierra:
```
Stians-Mac-mini:~ stian$ brew install homebrew/fuse/gitfs
==> Installing gitfs from homebrew/fuse
==> Using the sandbox
==> Downloading https://github.com/PressLabs/gitfs/archive/0.4.5.1.tar.gz
Already downloaded: /Users/stian/Library/Caches/Homebrew/gitfs-0.4.5.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/5c/79/5dae7494b9f5ed061cff9a8ab8d6e1f02db352f3facf907d9eb614fb80e9/virtualenv-15.0.2.tar.gz
Already downloaded: /Users/stian/Library/Caches/Homebrew/gitfs--homebrew-virtualenv-15.0.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/tmp/gitfs--homebrew-virtualenv-20170105-62989-mbq7ql/target --single-version-externally-managed --record=installed.txt
==> python -s /tmp/gitfs--homebrew-virtualenv-20170105-62989-mbq7ql/target/bin/virtualenv -p python /usr/local/Cellar/gitfs/0.4.5.1/libexec
==> Downloading https://files.pythonhosted.org/packages/86/8c/70aea8215c6ab990f2d91e7ec171787a41b7fbc83df32a067ba5d7f3324f/atomiclong-0.1.1.tar.gz
Already downloaded: /Users/stian/Library/Caches/Homebrew/gitfs--atomiclong-0.1.1.tar.gz
==> /usr/local/Cellar/gitfs/0.4.5.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/gitfs--atomiclong-20170105-62989-1ngho46/atomiclong-0.1.1
Last 15 lines from /Users/stian/Library/Logs/Homebrew/gitfs/03.pip:
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-zmQCsP-build/

READ THIS: https://git.io/brew-troubleshooting

Stians-Mac-mini:~ stian$ 
```

**Comment by ep1cman** [comment]
I can second this, on mac os sierra I get:

```
/usr/local/Cellar/gitfs/0.4.5.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/gitfs--pygit2-20170204-14230-4iga7m/pygit2-0.24.2
Last 15 lines from /Users/sebastiangoscik/Library/Logs/Homebrew/gitfs/06.pip:
  Removing source in /private/tmp/pip-pVmVTO-build
Command "/usr/local/Cellar/gitfs/0.4.5.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-pVmVTO-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xnnIXh-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/gitfs/0.4.5.1/libexec/include/site/python2.7/pygit2" failed with error code 1 in /private/tmp/pip-pVmVTO-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/gitfs/0.4.5.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-pVmVTO-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xnnIXh-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/gitfs/0.4.5.1/libexec/include/site/python2.7/pygit2" failed with error code 1 in /private/tmp/pip-pVmVTO-build/
```

**Comment by mvadim-** [comment]
You should try to install pip manually.

**Comment by vtemian** [comment]
I've updated the homebrew recipe. Can you please try again?
