### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'raven==5.27.0' distribution was not found and is required by gitfs

### ISSUE THREAD

**Issue by mvadim-** [PressLabs/gitfs#264]
I`ve tried to launch gitfs on mac os 10.12.2 but got an issue:

`mvadim-MacBook-Pro:~ mvadim$ gitfs
Traceback (most recent call last):
  File "/usr/local/bin/gitfs", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'raven==5.27.0' distribution was not found and is required by gitfs`

But raven with necessary version is installed:

`mvadim-MacBook-Pro:~ mvadim$ raven --v
5.27.0`

**Comment by mvadim-** [comment]
Issue was related to incorrect path for installed by pip modules.
