### ISSUE TITLE
Pygit2 issues

### ISSUE THREAD

**Issue by mvadim-** [presslabs/gitfs#266]
I have issues with FetchWorker:

```
February-08-2017 16:58:54 SyncWorker: Nothing to do right now, going idle
February-08-2017 16:58:54 SyncWorker: Set syncing event (0 pending writes)
February-08-2017 16:58:54 SyncWorker: Start syncing, first attempt.
February-08-2017 16:58:54 SyncWorker: Check if I'm ahead
February-08-2017 16:58:54 SyncWorker: Sync done, clearing
February-08-2017 16:58:55 FetchWorker: Lock fetching operation
February-08-2017 16:58:55 FetchWorker: Start fetching
February-08-2017 16:58:55 FetchWorker: ---Credentials <pygit2.remote.RemoteCallbacks object at 0x10712c650>----
February-08-2017 16:58:55 FetchWorker: ---upstream origin----
February-08-2017 16:58:55 FetchWorker: ---credentials <pygit2.remote.RemoteCallbacks object at 0x10712c650>----
February-08-2017 16:58:55 FetchWorker: Fetch failed
Traceback (most recent call last):
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/worker/fetch.py", line 48, in fetch
    was_behind = self.repository.fetch(self.upstream, self.branch, self.credentials)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/repository.py", line 149, in fetch
    remote.fetch(callbacks=credentials)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pygit2/remote.py", line 378, in fetch
    check_error(err)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
GitError: internal security trust error
February-08-2017 16:58:55 FetchWorker: Wait for 1800
February-08-2017 16:58:59 SyncWorker: Nothing to do right now, going idle
February-08-2017 16:58:59 SyncWorker: Set syncing event (0 pending writes)
February-08-2017 16:58:59 SyncWorker: Start syncing, first attempt.
February-08-2017 16:58:59 SyncWorker: Check if I'm ahead
February-08-2017 16:58:59 SyncWorker: Sync done, clearing
February-08-2017 16:59:04 SyncWorker: Nothing to do right now, going idle
February-08-2017 16:59:04 SyncWorker: Set syncing event (0 pending writes)
February-08-2017 16:59:04 SyncWorker: Start syncing, first attempt.
February-08-2017 16:59:04 SyncWorker: Check if I'm ahead
```

**Comment by vtemian** [comment]
We've just updated the pygit2 version.

Can you please check again with 0.5.1?
