### ISSUE TITLE
install on OSX fails

### ISSUE THREAD

**Issue by kontrafiktion** [presslabs/gitfs#267]
```==> /usr/local/Cellar/gitfs/0.4.5.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/gitfs--pygit2-20170228-92797-7wzgdw/pygit2-0.24.2
Last 15 lines from /Users/vivo/Library/Logs/Homebrew/gitfs/06.pip:
  Removing source in /private/tmp/pip-v_qgsL-build
Command "/usr/local/Cellar/gitfs/0.4.5.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-v_qgsL-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3uo_YN-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/gitfs/0.4.5.1/libexec/include/site/python2.7/pygit2" failed with error code 1 in /private/tmp/pip-v_qgsL-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/local/Cellar/gitfs/0.4.5.1/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-v_qgsL-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-3uo_YN-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/gitfs/0.4.5.1/libexec/include/site/python2.7/pygit2" failed with error code 1 in /private/tmp/pip-v_qgsL-build/
```

perhaps this PR already fixes it: https://github.com/Homebrew/homebrew-fuse/pull/100
But it introduces a dependency to its own hombrew-extras because (it seems) gitfs depends on libgit 0.24.1

OSX: 10.12.3

**Comment by vtemian** [comment]
The homebrew formula was updated. Can you please try again?
