### ISSUE TITLE
[mac os x sierra] raven==5.27.0 distribution was not found and is required by gitfs

### ISSUE THREAD

**Issue by khoan** [presslabs/gitfs#271]
```
$ brew --version
Homebrew 1.2.4
Homebrew/homebrew-core (git revision ff3c; last commit 2017-07-06)
$ uname -mrs
Darwin 16.6.0 x86_64
$ brew cask install osxfuse
# success
$ brew install gitfs
# success
$ gitfs http://52.64.121.123/issues.git issues
Traceback (most recent call last):
  File "/usr/local/bin/gitfs", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'raven==5.27.0' distribution was not found and is required by gitfs
```

**Comment by khoan** [comment]
tried to resolve dependency

```
$ cd /usr/local/Cellar/gitfs/0.4.5.1/libexec
$ bin/pip install raven==5.27.0
$ # fudge /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libgit2.rb according to https://github.com/Homebrew/homebrew-core/pull/2324/files#diff-e8ee420781a969273c7a80870a8bf6db
$ brew remove --ignore-dependencies libgit2
$ brew install libgit2
$ bin/pip install pygit2==0.24.1
$ gitfs http://52.64.121.123:issues.git issues
Traceback (most recent call last):
  File "/usr/local/bin/gitfs", line 11, in <module>
    load_entry_point('gitfs==0.4.5.1', 'console_scripts', 'gitfs')()
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/__init__.py", line 20, in mount
    start_fuse()
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/mounter.py", line 108, in start_fuse
    args = parse_args(parser)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/mounter.py", line 40, in parse_args
    return Args(parser)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 63, in __init__
    self.config = self.build_config(parser.parse_args())
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 72, in build_config
    return self.check_args(self.set_defaults(args))
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 142, in set_defaults
    value = value(args)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 173, in get_repo_path
    return tempfile.mkdtemp(dir="/var/lib/gitfs")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 333, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/var/lib/gitfs/tmpPZs8XF'
$ sudo !!
sudo gitfs http://52.64.121.123:issues.git issues
Traceback (most recent call last):
  File "/usr/local/bin/gitfs", line 11, in <module>
    load_entry_point('gitfs==0.4.5.1', 'console_scripts', 'gitfs')()
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/__init__.py", line 20, in mount
    start_fuse()
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/mounter.py", line 108, in start_fuse
    args = parse_args(parser)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/mounter.py", line 40, in parse_args
    return Args(parser)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 63, in __init__
    self.config = self.build_config(parser.parse_args())
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 72, in build_config
    return self.check_args(self.set_defaults(args))
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 142, in set_defaults
    value = value(args)
  File "/usr/local/Cellar/gitfs/0.4.5.1/libexec/lib/python2.7/site-packages/gitfs/utils/args.py", line 173, in get_repo_path
    return tempfile.mkdtemp(dir="/var/lib/gitfs")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 333, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/var/lib/gitfs/tmpZFBLGq'
$ # cried a little
```

**Comment by eleaner** [comment]
hi
is this issue still not fixed?

**Comment by wataash** [comment]
same for me

**Comment by vogler** [comment]
@khoan I tried what you did, but `bin/pip install pygit2==0.24.1` fails with `You need a compatible libgit2 version (v0.24.x)`.
By now `libgit2` is `0.28.1`. Sadly trying to install `0.24.1` with brew is another rabbit hole (it's not as easy as `brew install libgit2@0.24.1`); I tried some of the things mentioned [here](https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula) but all failed.

**Comment by vtemian** [comment]
The homebrew formula was updated. Can you please try again?
