### ISSUE TITLE
Error: DistributionNotFound: cffi==1.7.0

### ISSUE THREAD

**Issue by metux** [presslabs/gitfs#296]
On Ubuntu trusty (using the PPA):

Traceback (most recent call last):
  File "/usr/bin/gitfs/.bootstrap/_pex/pex.py", line 216, in execute
    working_set = self._env.activate()
  File "/usr/bin/gitfs/.bootstrap/_pex/environment.py", line 123, in activate
    self._working_set = self._activate()
  File "/usr/bin/gitfs/.bootstrap/_pex/environment.py", line 143, in _activate
    resolved = working_set.resolve(all_reqs, env=self)
  File "/usr/bin/gitfs/.bootstrap/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
DistributionNotFound: cffi==1.7.0

**Comment by vtemian** [comment]
We deprecated the trusty release and moved further with bionic and above (18.04, 19.04 and 19.10).
