### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by oxr463** [presslabs/gitfs#305]
```terminal
gitfs https://gitlab.com/oxr463/gentoo /usr/portage
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/handlers.py", line 823, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gitfs", line 11, in <module>
    load_entry_point('gitfs==0.4.5.1', 'console_scripts', 'gitfs')()
  File "/usr/local/lib/python3.5/dist-packages/gitfs-0.4.5.1-py3.5.egg/gitfs/__init__.py", line 20, in mount
    start_fuse()
  File "/usr/local/lib/python3.5/dist-packages/gitfs-0.4.5.1-py3.5.egg/gitfs/mounter.py", line 111, in start_fuse
    args = parse_args(parser)
  File "/usr/local/lib/python3.5/dist-packages/gitfs-0.4.5.1-py3.5.egg/gitfs/mounter.py", line 40, in parse_args
    return Args(parser)
  File "/usr/local/lib/python3.5/dist-packages/gitfs-0.4.5.1-py3.5.egg/gitfs/utils/args.py", line 65, in __init__
    self.config = self.build_config(parser.parse_args())
  File "/usr/local/lib/python3.5/dist-packages/gitfs-0.4.5.1-py3.5.egg/gitfs/utils/args.py", line 74, in build_config
    return self.check_args(self.set_defaults(args))
  File "/usr/local/lib/python3.5/dist-packages/gitfs-0.4.5.1-py3.5.egg/gitfs/utils/args.py", line 100, in check_args
    handler = SysLogHandler(address="/dev/log")
  File "/usr/lib/python3.5/logging/handlers.py", line 806, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib/python3.5/logging/handlers.py", line 834, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

gitfs -v
GitFS 0.4.5.1
```

**Comment by vtemian** [comment]
It looks like it can't connect to `/dev/log`.
Can you check if your logging service is running?
Maybe https://askubuntu.com/questions/861227/dev-log-is-missing-how-do-i-fix will help.
