### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by nickwebha** [presslabs/gitfs#318]
Been using this a lot (great work, by the way). I upgraded to Ubuntu 20.04 and now I am getting `/usr/bin/env: ‘python3.7’: No such file or directory`.

Fix on the way?

**Comment by vtemian** [comment]
Thanks, @nickwebha!

For now, Ubuntu 20.04 is not tested, but I'll take a look, hopefully, this week.

**Comment by nickwebha** [comment]
Any updates on this? Would be really helpful to be able to traverse Git repos in my GUI.

**Comment by ser** [comment]
Hi, any progress to make 20.04 PPA available?

**Comment by berryamin** [comment]
Working flawlessly on Ubuntu 20.04 with Python 3.8, as you can see below (patch included ^^)
```
kalou@shinwey:~/gitfs$ ./build/gitfs -v
GitFS 0.5.1

kalou@shinwey:~/gitfs$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

kalou@shinwey:~/gitfs$ git diff
diff --git a/Makefile b/Makefile
index bdc8074..d777b52 100644
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,7 @@ BUILD_DIR:=build
 VIRTUAL_ENV?=$(BUILD_DIR)/virtualenv
 
 TESTS?=tests
-PYTHON?=3.7
+PYTHON?=3.8
 TEST_DIR:=/tmp/gitfs-tests
 MNT_DIR:=$(TEST_DIR)/$(shell bash -c 'echo $$RANDOM')_mnt
 REPO_DIR:=$(TEST_DIR)/$(shell bash -c 'echo $$RANDOM')_repo

```

**Comment by nickwebha** [comment]
Thanks for the response!

A few things:
- The PPA does not support _focal_ so I had to change it to _eoan_.
- When I try to run gitfs from the PPA I get:
```
Traceback (most recent call last):
  File "/usr/bin/gitfs/.bootstrap/pex/pex.py", line 397, in execute
  File "/usr/bin/gitfs/.bootstrap/pex/pex.py", line 329, in _wrap_coverage
  File "/usr/bin/gitfs/.bootstrap/pex/pex.py", line 360, in _wrap_profiling
  File "/usr/bin/gitfs/.bootstrap/pex/pex.py", line 442, in _execute
  File "/usr/bin/gitfs/.bootstrap/pex/pex.py", line 540, in execute_entry
  File "/usr/bin/gitfs/.bootstrap/pex/pex.py", line 555, in execute_pkg_resources
  File "/home/nick/.pex/install/gitfs-0.5.1-py3.7.egg.74e262854927b65700f7abdf97c6affee9aa03a8/gitfs-0.5.1-py3.7.egg/gitfs/__init__.py", line 19, in mount
    from gitfs.mounter import start_fuse
  File "/home/nick/.pex/install/gitfs-0.5.1-py3.7.egg.74e262854927b65700f7abdf97c6affee9aa03a8/gitfs-0.5.1-py3.7.egg/gitfs/mounter.py", line 21, in <module>
    from pygit2 import Keypair, UserPass
  File "/home/nick/.pex/install/pygit2-0.28.2-py3.7-linux-x86_64.egg.18c8c1c5cf9cdabd12f9a2a4c24a8fdfe85720dd/pygit2-0.28.2-py3.7-linux-x86_64.egg/pygit2/__init__.py", line 35, in <module>
    from .blame import Blame, BlameHunk
  File "/home/nick/.pex/install/pygit2-0.28.2-py3.7-linux-x86_64.egg.18c8c1c5cf9cdabd12f9a2a4c24a8fdfe85720dd/pygit2-0.28.2-py3.7-linux-x86_64.egg/pygit2/blame.py", line 32, in <module>
    from .ffi import ffi, C
  File "/home/nick/.pex/install/pygit2-0.28.2-py3.7-linux-x86_64.egg.18c8c1c5cf9cdabd12f9a2a4c24a8fdfe85720dd/pygit2-0.28.2-py3.7-linux-x86_64.egg/pygit2/ffi.py", line 32, in <module>
    from ._libgit2 import ffi, lib as C
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```
- When trying to compile from source (after making your changes and running **make**) I get:
```
virtualenv --setuptools build/virtualenv -ppython3.8
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--app-data APP_DATA] [--clear-app-data] [--discovery {builtin}] [-p py] [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed]
                  [--activators comma_sep_list] [--clear] [--system-site-packages] [--symlinks | --copies] [--download | --no-download] [--extra-search-dir d [d ...]] [--pytoml version] [--pep517 version] [--urllib3 version]
                  [--certifi version] [--chardet version] [--setuptools version] [--pip version] [--html5lib version] [--msgpack version] [--distro version] [--ipaddr version] [--webencodings version] [--requests version]
                  [--distlib version] [--contextlib2 version] [--CacheControl version] [--retrying version] [--colorama version] [--wheel version] [--idna version] [--lockfile version] [--progress version] [--six version]
                  [--pyparsing version] [--packaging version] [--pkg_resources version] [--appdirs version] [--no-pytoml] [--no-pep517] [--no-urllib3] [--no-certifi] [--no-chardet] [--no-setuptools] [--no-pip] [--no-html5lib] [--no-msgpack]
                  [--no-distro] [--no-ipaddr] [--no-webencodings] [--no-requests] [--no-distlib] [--no-contextlib2] [--no-CacheControl] [--no-retrying] [--no-colorama] [--no-wheel] [--no-idna] [--no-lockfile] [--no-progress] [--no-six]
                  [--no-pyparsing] [--no-packaging] [--no-pkg_resources] [--no-appdirs] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: the following arguments are required: dest
make: *** [Makefile:46: build/virtualenv/bin/pip3.8] Error 2
```

**Comment by karawitan** [comment]
@nickwebha the "pip" targets are broken, please use the following commit as well https://github.com/karawitan/gitfs/commit/978dda64e111df789cf5c9b476b2d4d1c679f448

**Comment by The-Inamati** [comment]
Please can someone help me get this running on ubuntu 20.04? I really need this to work.

**Comment by gioppoluca** [comment]
A working version for 20.04 or most recent ubuntu versions could be usefull

**Comment by pmcdonald-metropolis** [comment]
Any update?

**Comment by ser** [comment]
Now the update rather to 22:04 is required...

**Comment by nickwebha** [comment]
I check this repository and issue every few months. Very sad to see the project die like this because it was great. If I knew Python I would fork it but I really do not have the bandwidth for that right now. I am now on 22.04 (sticking with the LTS releases).

Any way, still hoping for a modern update! :) Be well.
