### ISSUE TITLE
MacOS brew install gitfs fails

### ISSUE THREAD

**Issue by smolin** [presslabs/gitfs#322]
Looks like a library version mismatch?

`
$ brew install gitfs
$ gitfs
Traceback (most recent call last):
  File "/usr/local/Cellar/gitfs/0.5.2_3/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/gitfs/0.5.2_3/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/gitfs/0.5.2_3/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pygit2 1.1.1 (/usr/local/Cellar/gitfs/0.5.2_3/libexec/lib/python3.8/site-packages), Requirement.parse('pygit2==0.28.2'), {'gitfs'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gitfs", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/gitfs/0.5.2_3/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/local/Cellar/gitfs/0.5.2_3/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/gitfs/0.5.2_3/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/gitfs/0.5.2_3/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/Cellar/gitfs/0.5.2_3/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/Cellar/gitfs/0.5.2_3/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pygit2==0.28.2' distribution was not found and is required by gitfs
`

This doesn't help BTW:
`
$ brew install pygit2
Error: No available formula with the name "pygit2"
`

Mojave 10.14.6

**Comment by bgmonroe** [comment]
@smolin, pygit2 is a python module (so would be installed via pip3).  I ran into a similar issue (though not identical so take it with a grain of salt).  Now that FUSE is no longer in the Homebrew ecosystem (though install-able from the their GitHub repo), brew has to build gitfs from bottle (source, effectively) because it can't fulfill the FUSE dependency.  The error I get durriing the bottle build is that it fails compiling libgit2 (which is used by pygit2).  Though libgit2 is in fact in Homebrew, it's too recent (1.1.0) where, digging though the build logs, it seems that the version of pygit2 that is needed by gitfs is between 0.99.0 and 1.0.x) which isn't available though brew.  I'm not interested in gitfs enough to try building the right version from scratch to I'm moving on.  Hopefully this is useful (if not timely) info.  Good luck.

**Comment by antoine2711** [comment]
When trying to install from brew, I get this…

```
antoine$ brew install gitfs
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
Warning: gitfs has been deprecated because it is not maintained upstream!
gitfs: Linux is required for this software.
libfuse: Linux is required for this software.
Error: gitfs: Unsatisfied requirements failed this build.
```

Is it getting worst?

A.
