### ISSUE TITLE
ssh key is hardcoded to use id_rsa

### ISSUE THREAD

**Issue by mneilly** [presslabs/gitfs#334]
Thank you for your efforts with gitfs! I'm looking forward to attempting to use it to track my user config files.

It appears that gitfs is hardcoded to use id_rsa, does not respect settings in ~/.ssh/config and doesn't provide an alternative way to specify which key to use.

https://github.com/presslabs/gitfs/blob/cf92acc1fdb0bf93d5998f223d9ef7b285bd74b1/gitfs/utils/args.py#L188

Mounting fails with the following error:
```
~$ gitfs -o log=-,debug=true,foreground=true,repo_path=/home/mneilly/.cache/gitfs/home.git git@github.com:mneilly/home.git .home.gitfs
July-13-2020 09:27:55 MainThread: Cloning into /home/mneilly/.cache/gitfs/home.git
July-13-2020 09:28:04 MainThread: Error on cloning the repository: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gitfs/repository.py", line 198, in clone
    remote_url, path, checkout_branch=branch, callbacks=credentials
  File "/usr/local/lib/python3.6/site-packages/pygit2/__init__.py", line 263, in clone_repository
    check_error(err)
  File "/usr/local/lib/python3.6/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: Failed to authenticate SSH session: Unable to send userauth-publickey request
```

Direct cloning works (as expected):
```
~$ (cd /tmp && git clone git@github.com:mneilly/home.git)
Cloning into 'home'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
warning: You appear to have cloned an empty repository.
~$ 
```

~/.ssh/config:
```
Host github
 HostName github.com
 IdentityFile ~/.ssh/github
 IdentitiesOnly yes
```

**Comment by mneilly** [comment]
I missed that ssh_key exists in the code. It looks like it is missing in the help but using -o ssh_key=<keyfile> appears to already work. Sorry for the spam.

```
~$ gitfs -v
GitFS 0.5.1
~$ gitfs -h
usage: GitFS [-h] [-v] [-o O] remote_url mount_point

positional arguments:
  remote_url     repo to be cloned
  mount_point    where the repo should be mount

optional arguments:
  -h, --help     show this help message and exit
  -v, --version  show program's version number and exit
  -o O           other options: repo_path, user, group, branch, max_size,
                 max_offset, fetch_timeout, merge_timeout, ssh_user
```
